# services:
#   redis:
#     container_name: cache
#     image: redis
#     ports:
#       - 6379:6379
#     volumes:
#       - redis:/data

# volumes:
#   redis:
#     driver: local

version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
